### ISSUE TITLE
please

### ISSUE THREAD

**Issue by dongpu1813** [topachain/topa#1]
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile:4495: recipe for target 'libbitcoin_server_a-init.o' failed
make[2]: *** [libbitcoin_server_a-init.o] Error 4
make[2]: Leaving directory '/home/pool/comple/topa/src'
Makefile:8195: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/pool/comple/topa/src'
Makefile:681: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Comment by shadow-42** [comment]
Try building again please
